### ISSUE TITLE
Request to include your theme in themes.getnikola.com

### ISSUE THREAD

**Issue by ralsina** [hjacobs/srcco.de#1]
Hi!

Would it bother you if I did some git trickery to get your theme into themes.getnikola.com?

Of course, with full attribution and you can add a README.md to say anything you want!

Thanks in advance

**Comment by hjacobs** [comment]
sure, you can add my theme --- please note that I want to reserve the right to my hand-drawn images, but I hereby just license (the images) under CC BY-NC (Creative Commons Attribution + Noncommercial) :-)

**Comment by ralsina** [comment]
awesome! I'll do all the trickery later today.

**Comment by ralsina** [comment]
Added it at http://themes.getnikola.com/#srcco.de thanks so much for sharing this :-)
